app.value("aboutCompanyURL","https://raw.githubusercontent.com/tarunraj95/MEANpractice/master/AboutCompany.json");
app.value("customerServiceURL","https://raw.githubusercontent.com/tarunraj95/MEANpractice/master/CustService.json");
app.value("logoURL","https://raw.githubusercontent.com/tarunraj95/MEANpractice/master/logo.json");
app.value("socialShareURL","https://raw.githubusercontent.com/tarunraj95/MEANpractice/master/Social.json");
app.value("menuURL","https://raw.githubusercontent.com/karan-khanna/MeanPractice/master/nestedMenuList-better")
app.value("trendingNowURL","https://raw.githubusercontent.com/tarunraj95/MeanShoppingProject/master/trendingNow/trendingJson.txt");
app.value("newArrivalURL","https://raw.githubusercontent.com/Mukul001/puma.json/master/puma.json");
app.value("featuresURL","https://raw.githubusercontent.com/sunnyharsh/sunnyAll/master/FeaturesJson.json");
app.value("genderURL","https://raw.githubusercontent.com/kundan4all/json/master/gender.json");
app.value("footerURL","https://raw.githubusercontent.com/tarunraj95/MEANpractice/master/footer.json");